import { Resident, Transaction, Event, Announcement, MaintenanceRequest, ChatGroup } from '../types';
import { v4 as uuidv4 } from 'uuid';

export const INITIAL_RESIDENTS: Resident[] = [
  {
    id: '1',
    name: 'Dr. Gifty Naa Larteley Addico',
    email: 'gifty@estate.com',
    phone: '+233 24 123 4567',
    role: 'admin',
    houseNumber: '1',
    street: 'Densu Street',
    occupants: 1,
    paymentStatus: 'unpaid',
    totalDuesOwed: 300,
    initialsColor: '#10B981',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Madam Matilda Arthur',
    email: 'matilda@estate.com',
    phone: '+233 24 234 5678',
    role: 'treasurer',
    houseNumber: '2',
    street: 'Densu Street',
    occupants: 1,
    paymentStatus: 'unpaid',
    totalDuesOwed: 300,
    initialsColor: '#3B82F6',
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    name: 'Mr. T V/H Wallace',
    email: 'wallace@estate.com',
    phone: '+233 24 345 6789',
    role: 'resident',
    houseNumber: '1',
    street: 'Rose Avenue',
    occupants: 1,
    paymentStatus: 'paid',
    totalDuesOwed: 0,
    lastPaymentDate: '2024-12-15',
    initialsColor: '#F59E0B',
    createdAt: '2024-02-10',
  },
  {
    id: '4',
    name: 'Madam Jackie King',
    email: 'jackie@estate.com',
    phone: '+233 24 456 7890',
    role: 'secretary',
    houseNumber: '5',
    street: 'Rose Avenue',
    occupants: 2,
    occupantNames: ['Jackie King', 'James King'],
    paymentStatus: 'paid',
    totalDuesOwed: 0,
    lastPaymentDate: '2024-12-10',
    initialsColor: '#8B5CF6',
    createdAt: '2024-02-15',
  },
  {
    id: '5',
    name: 'Madam Rita Heyman',
    email: 'rita@estate.com',
    phone: '+233 24 567 8901',
    role: 'resident',
    houseNumber: '8',
    street: 'Rose Avenue',
    occupants: 1,
    paymentStatus: 'paid',
    totalDuesOwed: 0,
    lastPaymentDate: '2024-12-12',
    initialsColor: '#EC4899',
    createdAt: '2024-02-20',
  },
  {
    id: '6',
    name: 'Mr. Edem Apasu',
    email: 'edem@estate.com',
    phone: '+233 24 678 9012',
    role: 'resident',
    houseNumber: '3',
    street: 'Hibiscus Avenue',
    occupants: 1,
    paymentStatus: 'partial',
    totalDuesOwed: 150,
    lastPaymentDate: '2024-11-20',
    initialsColor: '#06B6D4',
    createdAt: '2024-03-05',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: uuidv4(),
    title: 'Monthly Dues - January 2025',
    description: 'Regular monthly maintenance dues',
    amount: 150,
    type: 'credit',
    category: 'Dues',
    date: '2025-01-15',
    status: 'completed',
    createdBy: '1',
    icon: 'wallet',
  },
  {
    id: uuidv4(),
    title: 'Road Maintenance Contribution',
    description: 'Pothole filling and road repair',
    amount: 500,
    type: 'debit',
    category: 'Maintenance',
    date: '2025-01-20',
    status: 'completed',
    createdBy: '2',
    icon: 'wrench',
  },
  {
    id: uuidv4(),
    title: 'New Year Celebration',
    description: 'Estate annual party and gathering',
    amount: 800,
    type: 'debit',
    category: 'Events',
    date: '2025-01-01',
    status: 'completed',
    createdBy: '1',
    icon: 'calendar',
  },
  {
    id: uuidv4(),
    title: 'Security Equipment Purchase',
    description: 'CCTV cameras and security lights',
    amount: 1200,
    type: 'debit',
    category: 'Projects',
    date: '2024-12-28',
    status: 'completed',
    createdBy: '2',
    icon: 'tool',
  },
  {
    id: uuidv4(),
    title: 'December Dues Collection',
    description: 'Monthly dues from residents',
    amount: 900,
    type: 'credit',
    category: 'Dues',
    date: '2024-12-31',
    status: 'completed',
    createdBy: '1',
    icon: 'wallet',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: uuidv4(),
    title: 'Estate Annual General Meeting',
    description: 'Yearly AGM where residents discuss budget, elections, and estate development plans.',
    startDate: '2025-02-15',
    endDate: '2025-02-15',
    location: 'Community Hall, Estate Center',
    image: 'https://img.icons8.com/color/512/conference.png',
    status: 'upcoming',
    attendees: 42,
    estimatedBudget: 500,
    organizer: '1',
    createdAt: '2025-01-10',
  },
  {
    id: uuidv4(),
    title: 'Community Cleanup Drive',
    description: 'Join us for a morning cleanup of the estate premises and common areas.',
    startDate: '2025-02-08',
    endDate: '2025-02-08',
    location: 'All Estate Streets',
    image: 'https://img.icons8.com/color/512/trash.png',
    status: 'upcoming',
    attendees: 28,
    organizer: '4',
    createdAt: '2025-01-05',
  },
  {
    id: uuidv4(),
    title: 'New Year Celebration',
    description: 'Festive gathering with food, music, and entertainment for all residents.',
    startDate: '2025-01-01',
    endDate: '2025-01-01',
    location: 'Estate Grounds',
    image: 'https://img.icons8.com/color/512/party.png',
    status: 'completed',
    attendees: 65,
    estimatedBudget: 1200,
    organizer: '1',
    createdAt: '2024-12-01',
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: uuidv4(),
    title: 'Planned Power Outage - February 2025',
    content: 'The estate will experience a planned power outage on February 10, 2025, from 9:00 AM to 2:00 PM for maintenance work on the main transformer. Please plan accordingly.',
    priority: 'high',
    category: 'Maintenance',
    image: 'https://img.icons8.com/color/512/lightning.png',
    author: '1',
    authorRole: 'admin',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-20',
    views: 156,
    likes: 0,
  },
  {
    id: uuidv4(),
    title: 'Water Supply Schedule - 2025',
    content: 'Updated water supply maintenance schedule. Water will be shut off on alternate Saturdays for pipe cleaning and repairs. Check the maintenance calendar for specific dates.',
    priority: 'medium',
    category: 'Utilities',
    image: 'https://img.icons8.com/color/512/water.png',
    author: '2',
    authorRole: 'treasurer',
    createdAt: '2025-01-18',
    updatedAt: '2025-01-18',
    views: 203,
    likes: 12,
  },
  {
    id: uuidv4(),
    title: 'Security Alert - Unauthorized Entry Attempts',
    content: 'Security team detected unauthorized entry attempts at the eastern gate. Enhanced security measures are in place. Report any suspicious activity immediately to the security desk.',
    priority: 'critical',
    category: 'Security',
    image: 'https://img.icons8.com/color/512/security.png',
    author: '1',
    authorRole: 'admin',
    createdAt: '2025-01-19',
    updatedAt: '2025-01-19',
    views: 289,
    likes: 45,
  },
  {
    id: uuidv4(),
    title: 'Reminder: January Dues Collection',
    content: 'Please ensure your January maintenance dues are paid by January 31, 2025. Payment methods: Bank transfer, Mobile money, or Cash at the estate office during working hours.',
    priority: 'medium',
    category: 'Finance',
    image: 'https://img.icons8.com/color/512/invoice.png',
    author: '2',
    authorRole: 'treasurer',
    createdAt: '2025-01-15',
    updatedAt: '2025-01-15',
    views: 124,
    likes: 8,
  },
  {
    id: uuidv4(),
    title: 'Residents Corner - Green Initiative 2025',
    content: 'We are launching a green initiative to make our estate more environmentally friendly. Suggestions welcome for tree planting, recycling programs, and solar installation.',
    priority: 'low',
    category: 'Community',
    image: 'https://img.icons8.com/color/512/tree.png',
    author: '4',
    authorRole: 'secretary',
    createdAt: '2025-01-12',
    updatedAt: '2025-01-12',
    views: 87,
    likes: 34,
  },
];

export const MOCK_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: uuidv4(),
    title: 'Pothole on Densu Street',
    description: 'Large pothole near house 3 causing safety hazard',
    category: 'general',
    priority: 'high',
    status: 'in-progress',
    location: 'Densu Street, near House 3',
    requesterName: 'Mr. Edem Apasu',
    requesterPhone: '+233 24 678 9012',
    createdAt: '2025-01-18',
    updatedAt: '2025-01-22',
    assignedTo: 'maintenance-team-1',
    estimatedCost: 250,
    actualCost: 280,
  },
  {
    id: uuidv4(),
    title: 'Broken Street Light - Rose Avenue',
    description: 'Street light near house 8 has been broken for 3 weeks',
    category: 'electrical',
    priority: 'medium',
    status: 'assigned',
    location: 'Rose Avenue, near House 8',
    requesterName: 'Madam Rita Heyman',
    requesterPhone: '+233 24 567 8901',
    createdAt: '2025-01-16',
    updatedAt: '2025-01-20',
    assignedTo: 'maintenance-team-2',
    estimatedCost: 150,
  },
  {
    id: uuidv4(),
    title: 'Leaking Gutter - House 5',
    description: 'Water leaking from main gutter during heavy rain',
    category: 'structural',
    priority: 'medium',
    status: 'open',
    location: 'House 5, Rose Avenue',
    requesterName: 'Madam Jackie King',
    requesterPhone: '+233 24 456 7890',
    images: ['https://img.icons8.com/color/512/water-drop.png'],
    createdAt: '2025-01-21',
    updatedAt: '2025-01-21',
    estimatedCost: 300,
  },
  {
    id: uuidv4(),
    title: 'Gate Hinge Repair',
    description: 'Main gate hinge is loose and squeaking',
    category: 'general',
    priority: 'low',
    status: 'completed',
    location: 'Estate Main Gate',
    requesterName: 'Estate Management',
    requesterPhone: '+233 24 123 4567',
    createdAt: '2025-01-10',
    updatedAt: '2025-01-15',
    assignedTo: 'maintenance-team-1',
    estimatedCost: 100,
    actualCost: 120,
    completionDate: '2025-01-15',
  },
];

export const MOCK_CHAT_GROUPS: ChatGroup[] = [
  {
    id: uuidv4(),
    name: 'Estate Administrators',
    description: 'Private group for estate management discussion',
    members: ['1', '2', '4'],
    createdBy: '1',
    createdAt: '2024-06-15',
    icon: 'https://img.icons8.com/color/512/admin.png',
  },
  {
    id: uuidv4(),
    name: 'Densu Street Residents',
    description: 'Group for Densu Street residents to share updates',
    members: ['1', '2', '6'],
    createdBy: '1',
    createdAt: '2024-07-20',
    icon: 'https://img.icons8.com/color/512/group.png',
  },
  {
    id: uuidv4(),
    name: 'General Announcements',
    description: 'Estate-wide announcements and updates',
    members: ['1', '2', '3', '4', '5', '6'],
    createdBy: '1',
    createdAt: '2024-01-01',
    icon: 'https://img.icons8.com/color/512/broadcast.png',
  },
];

export const STREETS = ['All Streets', 'Densu Street', 'Rose Avenue', 'Hibiscus Avenue', 'Odum Street'];
